/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[id]': typeof import('./components/catalog/[id].vue')['default']
    CategoriesGrid: typeof import('./components/CategoriesGrid.vue')['default']
    FiltersSidebar: typeof import('./components/catalog/FiltersSidebar.vue')['default']
    ProductGrid: typeof import('./components/catalog/ProductGrid.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHero: typeof import('./components/TheHero.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheSearchBar: typeof import('./components/TheSearchBar.vue')['default']
  }
}
